### PR TITLE
Fix guide formatting

### PR DESCRIPTION
**Pull request by pmuens**
Just another quick formatting fix while reading through the guide.

### CODE REVIEW

**Comment by RobGruhl** [comment]
Oops, sorry - didn't see this - and thanks!

**Comment by pmuens** [comment]
Thanks for merging! 👍

**Comment by erikerikson** [comment]
Thanks for contributing!  🎉 

Sorry it took us so long to merge.

**Comment by pmuens** [comment]
> Thanks for contributing! 🎉

🎉 

> Sorry it took us so long to merge.

Nah, no worries. I can 100% understand that sometimes things take longer to merge 😬

**Pull request merged**
